# Generated by Django 4.1 on 2022-08-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milkprice', models.FloatField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, null=True)),
                ('user_type', models.CharField(max_length=20, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managername', models.CharField(max_length=200)),
                ('vendorname', models.CharField(db_index=True, max_length=200, unique=True)),
                ('joiningdate', models.DateField(auto_now_add=True)),
                ('address', models.CharField(db_index=True, max_length=200)),
                ('vendorcontact', models.CharField(db_index=True, max_length=14)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendorledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=100000)),
                ('price', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('related_milkcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorledger', to='dairy.milkcategory')),
                ('related_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorledger', to='dairy.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='milkcategory',
            name='related_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MilkCategory', to='dairy.vendor'),
        ),
    ]
