# Generated by Django 4.1 on 2022-08-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMilkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milkprice', models.FloatField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='joining_data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vendorledger',
            name='date',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorledger',
            name='price',
            field=models.FloatField(db_index=True, default=0.0, max_length=1000),
        ),
    ]
