# Generated by Django 4.1 on 2022-08-10 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_customermilkcategory_profile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_milk_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customerledger', to='dairy.customermilkcategory')),
            ],
        ),
    ]
